-- phpMyAdmin SQL Dump
-- version 4.8.3
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Gegenereerd op: 26 sep 2019 om 13:29
-- Serverversie: 10.1.36-MariaDB
-- PHP-versie: 7.2.11

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `sustainablemoments`
--

-- --------------------------------------------------------

--
-- Tabelstructuur voor tabel `evenement`
--

CREATE TABLE `evenement` (
  `id` int(10) NOT NULL,
  `evenement_naam` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `dag` int(11) NOT NULL,
  `datum` date NOT NULL,
  `tijd` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `plaats` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `adres` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `kost` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `beschrijving_kort` longtext COLLATE utf8_unicode_ci NOT NULL,
  `beschrijving` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `beschrijving_engels` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `facebook_link` varchar(255) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Gegevens worden geëxporteerd voor tabel `evenement`
--

INSERT INTO `evenement` (`id`, `evenement_naam`, `dag`, `datum`, `tijd`, `plaats`, `adres`, `kost`, `beschrijving_kort`, `beschrijving`, `beschrijving_engels`, `facebook_link`) VALUES
(1, 'Mary Jane Presents Shoes for Thought', 27, '2019-09-27', '19.00 - 21.00', 'Mary Jane \r\nschoenenboetiek', 'Oosterstraat 23, Groningen', 'Gratis toegang/Free entrance', 'Het najaar komt eraan, dus tijd voor ons om de nieuwe collectie te mogen verwelkomen. Naast onze vaste merken voegen wij dit seizoen Ballūta toe aan onze collectie.', 'Het najaar komt eraan, dus tijd voor ons om de nieuwe collectie te mogen verwelkomen. Naast onze vaste merken voegen wij dit seizoen Ballūta toe aan onze collectie. Duurzame en vegan schoenen saai? Ballūta bewijst het tegendeel! Een bijzondere collectie ontwikkeld vanuit gerecyclede en nieuwe materialen op een ambachtelijke manier gemaakt. De schoenen zijn ontworpen door de Portugese Catarina Pedrosco die in haar collecties kiest tussen een mix van van high fashion, sustainability en kunst. Mary Jane heeft de eer om als eerste winkel met haar samen te werken.\r\n<br/><br/>\r\nNieuwsgierig? Kom de 27e langs voor een hapje, drankje, de nieuwste collectie en een modeshow in samenwerking met <a href=\"https://www.facebook.com/kokotoko050/\" class=\"a-leesmeer\" target=\"_blank\">KOKO TOKO Store for happy products & people</a> en <a href=\"https://www.facebook.com/odditywear.nl/\" class=\"a-leesmeer\" target=\"_blank\">Oddity</a>', 'No English translation', 'https://www.facebook.com/events/746477069116864/'),
(2, '050&Mode ft. Sustainable Moments', 28, '2019-09-28', 'Hele dag', 'Groningen City Centre', '', 'Gratis toegang/Free entrance', 'Na een Avant-Gardistische show in 2018 gaat 050&Mode dit jaar voor sustainable. Dat doen ze door samen te werken met Sustainable Moments.', 'Na een Avant-Gardistische show in 2018 gaat <a href=\"https://050enmode.nl/\" class=\"a-leesmeer\" target=\"_blank\">050&Mode</a> dit jaar voor sustainable. Dat doen ze door samen te werken met Sustainable Moments. Het resultaat? Een duurzame winkelroute langs verrassende zaakjes in Groningen. Veel winkels organiseren ook een tof event. Bovendien staat er dit jaar op de Grote Markt voor de eerste keer een groot podium, waar onder meer studenten van het Noorderpoort College en het Alfa College duurzame modecollecties presenteren. ', 'After last year\'s Avant-Gardistic show, <a href=\"https://050enmode.nl/\" class=\"a-leesmeer\" target=\"_blank\">050&Mode</a> is going sustainable in 2019. How? By collaborating with Sustainable Moments. The result is a sustainable shopping route along the surprising shops of Groningen. Most shops will also organize a fun, sustainable event. And, for the first time, a main stage will rise at Groningen\'s Grote Markt. Among others, students of Noorderpoort College and Alfa College will present sustainable fashion collections.', 'https://www.facebook.com/events/624341991390919/'),
(3, 'Klein Berlijn', 29, '2019-09-29', '10.00 - 17.00', 'Grote Markt', '', 'Gratis toegang/Free intrance', 'Inmiddels al vijf jaar een begrip in Groningen; Klein Berlijn. Op de laatste zondag van september wordt De Grote Markt een groot vintage walhalla.', 'Inmiddels al vijf jaar een begrip in Groningen; Klein Berlijn (<a href=\"https://www.facebook.com/kleinberlijngroningen/\" class=\"a-leesmeer\" target=\"_blank\">https://www.facebook.com/kleinberlijngroningen/</a>). Op de laatste zondag van september wordt De Grote Markt voor een dag een groot vintage walhalla. Verwacht wederom een mix van vintage kleding en accessoires, meubels, curiosa en andere hebbedingetjes. En natuurlijk zou Klein Berlijn niet compleet zijn zonder muziek gedraaid door lokale DJ\'s en heerlijke snacks van lokale foodtrucks.', 'Already known for five years in Groningen: Klein Berlijn. Like every year, on the last day of September, Groningen\'s Grote Markt will be the large vintage place-to-be. Expect a mix of clothing and accessories, furniture, and other curiosities. Plus, Klein Berlijn wouldn\'t be complete without our local DJ\'s playing music and delicious snacks from local food trucks. <a href=\"https://www.facebook.com/kleinberlijngroningen/\" class=\"a-leesmeer\" target=\"_blank\">https://www.facebook.com/kleinberlijngroningen/</a>', 'https://www.facebook.com/events/643796782776531/'),
(4, 'Docu Night + Dinner', 30, '2019-09-30', '18.30 - 21.30', 'Lust', 'Oude Kijk in Het Jatstraat 58, Groningen', 'Gratis Toegang/Free entrance', 'Onder het genot van een drankje kijken we de documentaire Before the Flood. We nemen een kijkje in de situatie van klimaatverandering.', 'Onder het genot van een drankje kijken we op deze avond de documentaire <a href=\"https://www.imdb.com/title/tt5929776/\" class=\"a-leesmeer\" target=\"_blank\">Before the Flood</a> van Leonardo DiCaprio. In deze documentaire neem je een kijkje in de situatie van klimaatverandering en het effect daarvan op natuur en samenleving. Na die tijd gaan we met elkaar in gesprek. Een avond vol gezelligheid, goede gesprekken en eye openers en ontdek wat jij kan doen voor de wereld van overmorgen. \r\n<br/><br/>\r\nOok kun je voor de film mee eten met een duurzaam diner, gekookt door Lust. Wil je mee eten? Reserveer dan een tafeltje bij <a href=\"https://www.facebook.com/LustGroningen/\" class=\"a-leesmeer\" target=\"_blank\">Lust</a>.', 'Enjoy an evening with drinks while watching Before the Flood, a documentary by Leonardo DiCaprio. It gives shocking insights in the world of climate change and the effects on nature and society. Afterwards, there will be time to discuss, a lowkey opportunity to exchange your ideas. Please join us for this evening with lots of fun, good conversations and eye openers and find out what you can do for the day after tomorrow. \r\n<br/><br/>\r\nBefore the movie starts, you can also join our sustainable dinner, made by Lust. Would you like to join us? Please make a reservation at <a href=\"https://www.facebook.com/LustGroningen/\" class=\"a-leesmeer\" target=\"_blank\">Lust</a>.', 'https://www.facebook.com/events/1102490293289919/'),
(5, 'Tweedehandswinkel DenkTank', 30, '2019-09-30', '09.00 - 11.00', 'The Student Hotel', 'Boterdiep 9, 9712 LH Groningen\r\n', 'Alleen voor genodigden ', 'Naast het inspireren van consumenten zetten we ons ook graag in voor ondernemers. Tijdens deze bijeenkomst gaan we ontdekken of we de tweedehandswinkels in de stad kunnen ondersteunen.\r\n', 'Naast het inspireren van consumenten zetten we ons ook graag in voor ondernemers. Tijdens deze bijeenkomst gaan we ontdekken of we de tweedehandswinkels in de stad kunnen ondersteunen. Wat zijn de verbindingen tussen de winkels? Zijn er kansen voor samenwerking? Hoe wordt omgegaan met textielafval? \r\n<br/><br/>\r\nWil je graag een uitnodiging ontvangen? Stuur ons dan een berichtje. ', 'No English translation', 'https://www.facebook.com/SustainableMoments/'),
(6, 'Denim Day: Sustainable Raw', 1, '2019-10-01', '16.00 - 22.00', 'The Student Hotel', 'Boterdiep 9, Groningen', 'Gratis toegang/Free entrance', 'Een avond volledig in het teken van denim! Hoe goed ken jij de wereld van denim? En welke duurzame opties zijn er tegenwoordig eigenlijk? ', 'Eindelijk ook in Groningen: een avond die volledig in het teken zal staan van denim!\r\n<br/><br/>\r\nHoe goed ken jij de wereld van denim? Wat weet je bijvoorbeeld over de productie van deze stof en het effect hiervan op de wereld? En, nog veel belangrijker, welke duurzame opties zijn er tegenwoordig eigenlijk?\r\n<br/><br/>\r\nHet wordt een inspirerende avond, waarin verschillende aspecten van denim aan bod komen. Er is bovendien een markt zijn waar tweedehands denim, duurzame denim en customized denim wordt verkocht. Ook kun je workshops volgen over hoe jouw denim te customizen en zo een tweede leven te geven. Neem dus je eigen oude denim mee en laat je inspireren wat je er allemaal mee kunt doen.\r\n<br/><br/>\r\nVerder zijn er lezingen en bed talks. We hebben fantastische sprekers, dus dit wil je niet missen. Wie komen er? Dat houden we nog even voor onszelf. Houd onze Facebook-pagina <a href=\"https://www.facebook.com/pg/SustainableMoments/posts/\" class=\"a-leesmeer\" target=\"_blank\">https://www.facebook.com/pg/SustainableMoments/posts/</a> \r\nin de gaten voor het laatste nieuws. \r\n', 'Finally in Groningen: an evening that will be completely devoted to denim!\r\n<br/><br/>\r\nHow well do you know the world of denim? What do you know about the fabric, where it\'s made, and what effect that has on our planet? And even more important: what are the sustainable options for denim? \r\n<br/><br/>\r\nIt will be an inspiring evening where everything will be about denim, including drinks and some snacks. There will be a small market with local and sustainable denim. You will also be able to participate in workshops about different ways to customize your denim, to give your old jeans a second life. So don\'t forget to bring your old ones to this event. \r\n<br/><br/>\r\nBesides the market and workshops we\'ll organize (bed) talks with fantastic icons from the world of denim. Who? We\'ll keep you in the dark for a little while longer. Check out our Facebook page <a href=\"https://www.facebook.com/pg/SustainableMoments/posts/\" class=\"a-leesmeer\" target=\"_blank\">https://www.facebook.com/pg/SustainableMoments/posts/</a>  for the most recent updates! ', 'https://www.facebook.com/events/664635807336697/'),
(7, 'Closet Sale', 3, '2019-08-03', '18.00 - 21.00', 'The Student Hotel', 'Boterdiep 9, Groningen', 'Gratis toegang/Free entrance', 'Tijdens de Closet Sale zullen jonge, hippe verkopers (dames en heren) hun prachtige kleding, in maten van S tot XL, meenemen om te verkopen. ', 'Wij toveren op deze avond de foyer van The Student Hotel om tot een ware vintage boetiek. Tijdens de Closet Sale zullen een tiental jonge, hippe verkopers (dames en heren) hun prachtige kleding, in maten van S tot XL, meenemen om te verkopen. Er is voor ieder wat wils! Denk aan vintage juweeltjes of duurzame tweedehands items, alles is er te vinden. \r\nCash meenemen is erg handig maar er zal ook mogelijkheid zijn te pinnen. De items zullen geen vast prijskaartje hebben dus ga gerust in alle redelijkheid de onderhandeling met de verkoper aan. Geef op deze manier nieuw leven aan prachtige kledingstukken. \r\n', 'This evening, we\'ll transform the foyer of the Student Hotel into an amazing vintage boutique. During the Closet Sale, a group of young fashion lovers (boys and girls) will bring their wardrobe to sell. You will find sizes from S to XL. These fashion lovers all have their own style, which means there will definitely be something for everyone. Vintage gems, but also classic and chic items of clothing. There won\'t be any set prices, so feel free to negotiate a good price for you and give the items a new life. \r\n', 'https://www.facebook.com/events/2287351551387596/'),
(8, 'Docu Night + Drinks', 4, '2019-10-04', '19.30 - 22.30', 'Lust', 'Oude Kijk in Het Jatstraat 58, Groningen', 'Gratis toegang/Free entrance', 'Kijk met ons de documentaire Before the Flood. Voor en na de documentaire is er tijd om ervaringen met elkaar uit te wisselen. ', 'Kijk op deze avond met ons de documentaire <a href=\"https://www.imdb.com/title/tt5929776/\" class=\"a-leesmeer\" target=\"_blank\">Before the Flood</a>, van niemand minder dan Leonardo DiCaprio. Iedereen is welkom, want voor iedereen is het onderwerp relevant. Voor en na de documentaire is er tijd om onder het genot van een drankje idee&#235;n en ervaringen met elkaar uit te wisselen. Jij bent niet de enige met vragen en onduidelijkheden over dit onderwerp. Ga ongedwongen het gesprek met elkaar aan, wissel tips uit en ga naar huis met een dosis nieuwe inzichten. ', 'Join us this evening to watch the documentary Before the Flood, by none other than Leonardo DiCaprio. Everyone\'s welcome this evening, since this topic is relevant for everyone. Before and after the documentary, there will be time to enjoy drinks and discuss ideas and experiences. You\'re not the only one with questions and uncertainties. We\'re looking forward to meet you, exchange ideas and go home filled with new energy. ', 'https://www.facebook.com/events/383709849009862/'),
(9, 'Clothing Swap', 5, '2019-10-05', '11.00 - 17.00', 'Het Floreshuis', 'Floresplein 19, Groningen', 'Entrance &#8364;1,- (incl. one free drink)', 'Heb jij pareltjes van kledingstukken in je kast hangen, maar draag je deze nooit meer? Neem jouw gedragen (maar schone!) kleding mee naar onze kledingruildag. ', 'Heb jij pareltjes van kledingstukken in je kast hangen, maar draag je deze nooit meer? En vind je het zonde om ze weg te gooien? Dit is je kans! Neem jouw gedragen (maar schone!) kleding mee naar onze kledingruildag. Maak iemand anders blij met jouw kleding en vul op een duurzame manier jouw kledingkast met \'nieuwe\' items. Of je nou 1 of 10 items meeneemt: je kan met een volle tas naar huis. Neem vooral ook schoenen, hoeden en andere accessoires mee waarvan je denkt een ander blij mee te kunnen maken. \r\n<br/><br/>\r\nVoor de ouders: Drop je kind in onze speelhoek en struin lekker door al het moois dat wordt aangeboden.\r\n<br/><br/>\r\nJe bent de hele dag vrij om kleding in te brengen en mee te nemen. ', 'Do you have some beautiful pieces in your wardrobe that you don\'t wear anymore? but are too good to just throw away? And do you think it\'s a shame to throw them away? This is your chance! Take your worn (but clean!) clothes with you to our Sustainable ClothingSwap. Make someone else happy with your golden oldies and and fill your wardrobe with \'new\' items in a sustainable way. Whether you bring 1 or 10 items: you can go home with a full bag. Be sure to bring shoes, hats and other accessories that you think can make someone else happy. \r\n<br/><br/>\r\nFor the parents: Drop your child in our play corner and stroll through all the beauties that are offered.\r\n<br/><br/>\r\nYou are free to bring in and take along clothes all day long.', 'https://www.facebook.com/events/490441804856060/'),
(10, 'Oosterstraatfeest', 28, '2019-09-28', '11.00 - 17.00', 'Oosterkwartier Groningen', 'Oosterstraat, Groningen', 'Gratis toegang/Free entrance', 'Alweer voor het zesde jaar komt Ondernemersvereniging Oosterkwartier met het Oosterstraatfeest. Een bruisend evenement dat de Oosterstraat en de Carolieweg een dag lang in de spotlights zet. ', 'Het Oosterstraatfeest is ieder jaar net weer een beetje anders. Alle winkeliers en organisaties uit de straat krijgen een kraam tot hun beschikking en beslissen zelf of en hoe ze hier invulling aan willen geven. \r\n<br/><br/>\r\nNaast de markt is er dit jaar voor jong en oud volop vertier in het Oosterkwartier. Er zullen vele optredens zijn en kinderen kunnen bijvoorbeeld hun helden Elsa en Spiderman ontmoeten. \r\n<br/><br/>\r\nHet Oosterstraatfeest valt dit jaar samen met de eerste editie van het SuMoFest en daarom hebben meerdere winkeliers hierbij aangehaakt. Samen staan we sterker! Kom langs en ervaar de gezelligheid van het Oosterkwartier en zie ook wat vele winkeliers in de Oosterstraat al doen op het gebied van duurzaamheid. Zien we je daar?\r\n', 'No English translation', 'https://www.facebook.com/OosterkwartierGroningen/'),
(11, 'Het Goede Doel van de Groene Stoel', 2, '2019-10-02', '17.30 - 22.00', 'De Groene Stoel', 'Gedempte Zuiderdiep 26, 9711 HH Groningen', 'Entrance &#8364;25,-', 'Wil jij tijdens de week van Sustainable Moments kennismaken met de Nieuwe Groningers en meer? Dan ben je op woensdag 2 oktober vanaf 17:30 uur bij ons aan het juiste adres.', 'Wil jij tijdens de week van Sustainable Moments kennismaken met de Nieuwe Groningers, proeven van hun heerlijke gerechten en het kindertehuis BeHoCa in Kenia steunen met jouw bezoek? Dan ben je op woensdag 2 oktober vanaf 17:30 uur bij ons aan het juiste adres.\r\nOnze stagiaires maken een heerlijk driegangendiner met allemaal kleine hapjes en de opbrengst van dit diner gaat naar BeHoCa.\r\n<br/><br/>\r\nWil jij weten wat voor prachtigs BeHoCa doet en hoe zij jongens op weg helpen naar een betere toekomst, ga dan naar <a href=\"http://www.behoca.nl/\" class=\"a-leesmeer\" target=\"_blank\">www.behoca.nl</a>. Het diner kost &#8364;25,-.\r\nReserveer jouw plekje via de website of telefonisch. \r\n', 'No English translation', 'https://www.facebook.com/events/2403257276628469/'),
(12, 'Knutselen met Afval', 28, '2019-09-28', '10.00 - 17.00', 'Grote Markt', '', 'Kinderen van alle leeftijden', 'De Groningen City Club organiseert in samenwerking met de vier straten: Oude Kijk in \'t Jatstraat / Stoeldraaierstraat / Zwanestraat en Kromme Elleboog de activiteit \"Knutselen met Afval\". Ook met kinderen sluiten we daardoor aan op  de thema\'s duurzaamheid en circulaire economie die tijdens Sustainable Moments centraal staan.', '<h5 class=\"p-donkergroen font-weight-bold\">Update 24 september 2019</h5>\r\nAlle deelnemende ondernemers zijn al druk bezig om afval in te zamelen. Karton, plastic, dopjes, kledinghangers, je kunt het zo gek niet bedenken of het wordt verzameld. In totaal doen al meer dan 20 ondernemers mee en dat aantal zal waarschijnlijk nog wel gaan oplopen. Op vrijdag 27 september gaan we al het afval ophalen, zodat iedereen zich op vrijdag de 28ste op de Grote Markt kan uitleven in de knutselkeet. Ook kinderopvang SKSG gaat mee knutselen op hun centrumlocatie. De kunstwerken zullen volgende week in de etalages worden geplaatst! Benieuwd welke ondernemers allemaal mee doen? Houd onze berichtgeving in de gaten!\r\n<br/><br/>\r\n<br/><br/>\r\n<h5 class=\"p-donkergroen font-weight-bold\">Knustelen met afval</h5>\r\nDe Groningen City Club organiseert in samenwerking met de vier straten: Oude Kijk in \'t Jatstraat / Stoeldraaierstraat / Zwanestraat en Kromme Elleboog de activiteit \"Knutselen met Afval\". Ook met kinderen sluiten we daardoor aan op  de thema\'s duurzaamheid en circulaire economie die tijdens Sustainable Moments centraal staan.\r\n<br/><br/>\r\nKinderen van alle leeftijden kunnen zich op deze dag uitleven met het (schone) afval dat ondernemers in de vier genoemde straten hebben verzameld. Uit alle kunstwerken selecteren wij de mooiste, beste en meest creatieve en die worden geplaatst in de etalages van &#233;&#233;n van de deelnemende winkels. Een professionele jury gaat uit al deze kunstwerken vervolgens een top 3 samenstellen en daar hebben we mooie prijzen voor! Ook voor kinderen die niet in de prijzen vallen hebben we een leuke troostprijs. Dus kom gezellig knutselen op de Grote Markt en wie weet hangt jouw kunstwerk binnenkort in &#233;&#233;n van de deelnemende winkels!', '', 'https://www.facebook.com/pages/category/Social-Club/Groningen-City-Club-201538606580319/');

-- --------------------------------------------------------

--
-- Tabelstructuur voor tabel `winkels`
--

CREATE TABLE `winkels` (
  `id` int(10) NOT NULL,
  `winkel_naam` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `beschrijving_kort` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `beschrijving` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `straat_naam` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `straat_nummer` char(10) COLLATE utf8_unicode_ci NOT NULL,
  `postcode` char(7) COLLATE utf8_unicode_ci NOT NULL,
  `stad` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `telefoon` char(15) COLLATE utf8_unicode_ci NOT NULL,
  `website` varchar(255) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Gegevens worden geëxporteerd voor tabel `winkels`
--

INSERT INTO `winkels` (`id`, `winkel_naam`, `beschrijving_kort`, `beschrijving`, `straat_naam`, `straat_nummer`, `postcode`, `stad`, `telefoon`, `website`) VALUES
(1, 'De Musjes ', 'Met het kopen bij deze kinderkledingwinkel help je als consument de planeet. Het assortiment van Musjes is namelijk vrij van kinderarbeid en garandeert fairtrade productie en natuurlijke materialen.', 'Met het kopen bij deze kinderkledingwinkel help je als consument de planeet. Het assortiment van Musjes is namelijk vrij van kinderarbeid en garandeert fairtrade productie en natuurlijke materialen. Musjes gaat zich de komende tijd bezighouden met de verduurzaming van de toelevering naar de winkel om zo nog groener te worden.', 'Zwanestraat', '25', '9712 CJ', 'Groningen', '+31 50 785 0720', 'https://www.musjes.com/'),
(2, 'Marquant Department ', 'Een winkel met prachtige merkkleding, waarvan het grootste gedeelte van kleding van duurzame merken afkomstig is. Ook kan je deze winkel vinden in de app \"Eerlijk winkelen\".', 'Een winkel met prachtige merkkleding, waarvan het grootste gedeelte van kleding van duurzame merken afkomstig is. Ook kan je deze winkel vinden in de app \"Eerlijk winkelen\". De ambitie van Marquant Department is om hun volledige assortiment duurzaam in te kopen.  ', 'Oude Boteringestraat', '1-1', '9712 GA', 'Groningen', '+31 50 230 3062', 'https://www.marquant-department.nl/'),
(3, 'Het Land van Kokanje', 'Dit restaurant gebruikt alternatieve bereidingswijzen om hiermee afval te verminderen. Daarnaast kan je hier genieten van heerlijke gerechten gemaakt met seizoensproducten.', 'Dit restaurant gebruikt alternatieve bereidingswijzen om hiermee afval te verminderen. Daarnaast kan je hier genieten van heerlijke gerechten gemaakt met seizoensproducten. Het Land van Kokanje focust zich al op de vermindering van gas en stroom, maar hebben de ambitie hun pand beter te isoleren om hiermee nog meer te besparen. ', 'Oude Boteringestraat', '9', '9712 GB', 'Groningen', '+31 50 318 0622', 'https://www.landvankokanje.nl/'),
(4, 'Simsalabim', 'Deze eigengereide winkel heeft een prachtig assortiment aan duurzame merken. Simsalabim let bij inkoop op natuurlijke materialen en de werkomstandigheden waarin de kleding wordt gemaakt.', 'Deze eigengereide winkel heeft een prachtig assortiment aan duurzame merken. Simsalabim let bij inkoop op natuurlijke materialen en de werkomstandigheden waarin de kleding wordt gemaakt. Uiteraard krijg je die goede kleding alleen mee naar huis is een papieren tasje. ', 'Folkingestraat', '12', '9711 JW', 'Groningen', '+31 50 312 3727', 'https://simsalabimwebshop.com/'),
(5, 'Tim Tom', 'Iets wat als hobby begon veranderde in een stijlvolle woonwinkel met een prachtig assortiment aan tweedehands meubels en woonaccessoires. Alle producten van Tim Tom krijgen bij hun klanten een nieuw leven. ', 'Iets wat als hobby begon veranderde in een stijlvolle woonwinkel met een prachtig assortiment aan tweedehands meubels en woonaccessoires. Alle producten van Tim Tom krijgen bij hun klanten een nieuw leven. Wat leuk is om te weten dat Tim Tom hun verpakkingsmateriaal zoveel mogelijk hergebruikt. Zo komt alles netjes, maar ook milieuvriendelijk bij de klant. ', 'Nieuwe Ebbingestraat', '19', '9712 NC', 'Groningen', '+31 6 50915888', 'https://www.tim-tom.nl/'),
(6, 'Heksenketel', 'Deze damesmode zaak wordt gerund door Groningse modemakers. Dit betekent een assortiment van lokale producten die CO2 neutraal in de winkel komen.', 'Deze damesmode zaak wordt gerund door Groningse modemakers. Dit betekent een assortiment van lokale producten die CO2 neutraal in de winkel komen. Daarnaast heb je de kans om in Heksenketel de maker te ontmoeten. Wist je trouwens dat door het kopen bij deze kleinschalige makers dit gepaard gaat met veel minder afval? ', 'Folkingestraat', '12b', '9711 JW', 'Groningen', '+31 50 313 6690', 'http://www.heksenketelmode.nl/'),
(7, 'Mary Jane Schoenenboetiek', 'Deze chique boetiek verkoopt voornamelijk schoenen die ambachtelijk worden gemaakt in kleinschalige Europese fabrieken. Ook zijn er bij Mary Jane vegan schoenen te vinden.', 'Deze chique boetiek verkoopt voornamelijk schoenen die ambachtelijk worden gemaakt in kleinschalige Europese fabrieken. Ook zijn er bij Mary Jane vegan schoenen te vinden. De ondernemers achter Mary Jane snappen de struggle van andere ondernemers omtrent duurzaamheid, maar adviseren je niet tegen te laten houden! Elke stap naar duurzaamheid is er 1 en het hoeft dus niet allemaal in 1 keer perfect. De ambitie van Mary Jane is om een eigen duurzame collectie te ontwikkelen. ', 'Oosterstraat', '23', '9711 NN', 'Groningen', '+31 50 280 7592', 'https://www.maryjaneboetiek.com/'),
(8, 'DieZijner', 'Dit is een kledingzaak met aandacht voor de klant. Het assortiment van DieZijner kenmerkt zich aan tijdloze kleding die met aandacht is gemaakt.', 'Dit is een kledingzaak met aandacht voor de klant. Het assortiment van DieZijner kenmerkt zich aan tijdloze kleding die met aandacht is gemaakt. Zo vind je alleen kledingstukken van natuurlijke materialen in deze winkel. Ook is er aandacht voor toelevering door duurzaam transport en duurzame energie in de winkel. Het liefste wil Die Zijner in de toekomst samenwerken met andere ondernemingen om de verpakkingsmateriaal van binnenkomende en uitgaande goederen te verduurzamen. ', 'Zwanestraat', '29', '9712 CJ', 'Groningen', '+31 6 34569089', 'http://diezijner.eu/'),
(9, 'Stadsakker', 'Of je nu opzoek bent naar potgrond, een boeket, groentes, eieren of tuingereedschap. De Stadsakker heeft voor ieder wat wils een duurzame oplossing.', 'Of je nu opzoek bent naar potgrond, een boeket, groentes, eieren of tuingereedschap. De Stadsakker heeft voor ieder wat wils een duurzame oplossing. Ook is de Stadsakker een leerbedrijf waar nieuwe kleinschalige kwekers worden opgeleid. Leuk is om te weten dat de Stadsakker geen groentes weggooien, dit wordt namelijk kippenvoer. En ja je kan ook hun eitjes bij de Stadsakker kopen. Verser kan niet! ', 'Oude Kijk in Het Jatstraat', '38', '9712 EK', 'Groningen', '+31 50 313 1739', 'http://www.stadsakker.nl/'),
(10, 'Schone Zaken', 'Deze modezaak is al sinds 1997 pioiner en specialist in Eco-Bio-Fairwear kleding. Dit zie je uiteraard terug in een assortiment van 100% verantwoorde kleding.', 'Deze modezaak is al sinds 1997 pioiner en specialist in Eco-Bio-Fairwear kleding. Dit zie je uiteraard terug in een assortiment van 100% verantwoorde kleding. Tijdens Sustainable Moments heb je een mooie kans om deze eco-producten eens uit te proberen, door een mooie aanbieding op bamboe sokken. ', 'Nieuwe Ebbingestraat', '16', '9712 NK', 'Groningen', '+31 50 589 1515', 'http://www.schonezaken.nl/'),
(11, 'Terre Des Hommes ', 'Een tweedehands zaak met een breed assortiment aan spullen. Denk hierbij aan boeken, spelletjes en kleding.', 'Een tweedehands zaak met een breed assortiment aan spullen. Denk hierbij aan boeken, spelletjes en kleding. Al het geld wat verdiend wordt bij Terre Des hommes wordt gebruikt om uitbuiting van kinderen te stoppen.', 'Nieuwe Ebbingestraat', '83', '9712 NG', 'Groningen', '+31 50 577 0112', 'https://www.terredeshommes.nl/winkels/groningen'),
(12, 'De Groene Stoel', 'De naam van de zaak laat al zien hoe groen het hart is van de ondernemer achter De Groene Stoel is. Ze werken samen met lokale en duurzame bedrijven.', 'De naam van de zaak laat al zien hoe groen het hart is van de ondernemer achter De Groene Stoel is. Ze werken samen met lokale en duurzame bedrijven. Daarnaast bieden ze een vernieuwend traject aan om \"nieuwe Groningers\" te helpen integreren in onze samenleving en op de arbeidsmarkt.', 'Gedempte Zuiderdiep', '26', '9711 HH', 'Groningen', '+31 50 230 2628', 'https://www.degroenestoel.nl/'),
(13, 'De Proof', 'Je kan zelfs in Groningen een duurzame kapsalon vinden! Het assortiment shampoos die je bij De Proof kan vinden, hebben een duurzame verpakking.', 'Je kan zelfs in Groningen een duurzame kapsalon vinden! Het assortiment shampoos die je bij De Proof kan vinden, hebben een duurzame verpakking. Daarnaast besteedt De Proof aandacht aan het verduurzamen van de winkel, dit door middel van infrarood verwarming. De Proof heeft de ambitie om nieuwe douchekoppen aan te schaffen die bijdragen het water en energieverbruik van de zaak te verminderen. De duurzame tip van de ondernemer is: Begin bij jezelf, hoe meer jij je verdiept hoe leuker het wordt. Praat er ook over met je klanten, dit is een gegarandeerd succes! ', 'Grote Kromme Elleboog', '3', '9712 BJ', 'Groningen', '+31 50 230 0861', 'http://the-proof.nl/'),
(14, 'Laif & Nuver', 'Deze prachtige woonwinkel heeft hun eerste stappen gemaakt in het verduurzamen van hun winkel. Dit door duurzaam om te gaan met energie en het hergebruiken van verpakkingen.', 'Deze prachtige woonwinkel heeft hun eerste stappen gemaakt in het verduurzamen van hun winkel. Dit door duurzaam om te gaan met energie en het hergebruiken van verpakkingen. Laif & Nuver heeft de ambitie om een nieuw pand te vinden die volledig duurzaam functioneert.', 'Vismarkt', '40', '9711 KT', 'Groningen', '+31 50 850 0562', 'https://www.laifennuver.nl/'),
(15, 'Oddity', 'Dames kunnen van alles vinden bij Oddity; duurzame merken, tweedehands kleding en zelfs met regelmaat live muziek. Daarnaast is Oddity intern bewust bezig.', 'Dames kunnen van alles vinden bij Oddity; duurzame merken, tweedehands kleding en zelfs met regelmaat live muziek. Daarnaast is Oddity intern bewust bezig. De inrichting de winkel is tweedehands en medewerkers komen uitsluitend met het OV naar hun werk. Oddity heeft de ambitie om te innoveren, om zo duurzame kleding laagdrempelig aan te bieden. Deze plannen zijn in de maak.', 'Oosterstraat', '16', '9711 NT', 'Groningen', '+31 50 750 1497', 'https://m.facebook.com/odditywear.nl'),
(16, 'KOKOTOKO', 'Hier staat duurzaamheid in alle opzichten centraal. Waardoor je alle producten van KOKOTOKO met een gerust hart kunt aanschaffen.', 'Hier staat duurzaamheid in alle opzichten centraal. Waardoor je alle producten van KOKOTOKO met een gerust hart kunt aanschaffen. Alle dames en heren kleding is namelijk fairtrade en biologisch gecertificeerd. Ook kan je bij KOKOTOKO diverse lifestyle producten kopen, die je op weg helpen met het verduurzamen van je leven. Ondanks deze mooie producten worden deze alsnog in plastic aangeleverd, KOKOTOKO wil hier graag een oplossing voor vinden.', 'Oosterstraat', '26', '9711 NV', 'Groningen', '-', 'http://kokotoko.nl/'),
(17, 'ReShare Store', 'Dit initiatief van Het Leger Des Heils is begonnen in Groningen en heeft ondertussen 10 winkels door het hele land verspreid. Alles in de winkel is tweedehands inclusief het interieur.', 'Dit initiatief van Het Leger Des Heils is begonnen in Groningen en heeft ondertussen 10 winkels door het hele land verspreid. Alles in de winkel is tweedehands inclusief het interieur. Ook wordt er bewust omgegaan met logistiek. Daarnaast krijgt de klant zijn aankopen uitsluitend mee in een papieren tasje.', 'Oosterstraat', '41', '9711 NR', 'Groningen', '+31 50 360 3333', 'https://www.resharestore.nl/index.php'),
(18, 'BAQ', 'Bij BAQ kan je genieten van heerlijk brood, taart en koek, die elke ochtend vers gebakken worden in de eigen bakkerij.', 'Bij BAQ kan je genieten van heerlijk brood, taart en koek, die elke ochtend vers gebakken worden in de eigen bakkerij. BAQ maakt gebruik van lokale grondstoffen, zo kunnen ze je precies vertellen waar jouw broodje vandaan komt/ Hiermee steun je de Groningse economie.', 'Folkingestraat', '19', '9711 JS', 'Groningen', '+31 50 553 5911', 'https://www.baq.nl/'),
(19, 'Find050', 'Find your treasures bij Find050. Deze tweedehands kledingwinkel geeft jouw kleding weer een tweede leven.', 'Find your treasures bij Find050. Deze tweedehands kledingwinkel geeft jouw kleding weer een tweede leven. Ja, je leest het goed. Je kan bij Find050 ook zelf winkeltje spelen. Je brengt jouw pareltjes die te lang niet uit de kast zijn gekomen naar Find en daar mag het dan een aantal weken in de winkel hangen. Wordt het verkocht krijg je een gedeelte van de opbrengst, zo niet gaat jouw kleding naar Kledingbank Maxima of je neemt je items zelf weer mee naar huis. Op deze manier help je hier ook weer een ander mee.', 'Damsterdiep', '42', '9711 SM', 'Groningen', '+31 6 20449374', 'https://www.findvintage.nl/'),
(20, 'MAHALO', 'Deze pas geopende lunchzaak zet zich in voor jouw gezondheid en het milieu. Zo verkoopt Mahalo alleen biologische en plantaardige producten.', 'Deze pas geopende lunchzaak zet zich in voor jouw gezondheid en het milieu. Zo verkoopt Mahalo alleen biologische en plantaardige producten die ook overwegend lokaal geproduceerd zijn. Daarnaast is het leuk om te weten dat het take-away materiaal van Mahalo biologisch afbreekbaar is en dat ze spoedig elektrisch zullen koken.', 'Verlengde Grachtstraat', '1', '9717 GD', 'Groningen', '-', 'http://www.mahalo.nu/'),
(21, 'MamaMini', 'Een bekende naam in Groningen. Dat is ook niet zo gek, want Mamamini is namelijk niet zomaar een kringloopwinkel.', 'Een bekende naam in Groningen. Dat is ook niet zo gek, want Mamamini is namelijk niet zomaar een kringloopwinkel. Bijna alle opbrengsten van Mamamini gaan weer terug naar Groningers. Ieder jaar wordt een doel gekozen, zoals bijvoorbeeld juridische ondersteuning voor minima. Daarnaast scheidt Mamamini al het afval van de producten die de winkel niet halen en worden er laagdrempelige werkplekken gecre?erd.', 'Damsterdiep', '307', '9713 EH', 'Groningen', '+31 50 313 2200', 'https://www.mamamini.nl/'),
(22, 'Cledingraad', 'Een mooie mannenmode zaak met een prachtig pand in de binnenstad. Mannen kunnen bij Cledingraad terecht voor diverse duurzame merken.', 'Een mooie mannenmode zaak met een prachtig pand in de binnenstad. Mannen kunnen bij Cledingraad terecht voor diverse duurzame merken, zoals ook een aantal merken die je niet in andere winkels op onze winkelroute kan vinden. Cledingraad heeft de ambitie om hun volledige collectie nog verder te verduurzamen.', 'Zwanestraat', '9', '9712 CH', 'Groningen', '+31 50 851 1855', 'http://www.cledingraad.nl/'),
(23, 'Spaak', 'Bij ons zit duurzaamheid verstopt in alles wat we doen. De horeca is voorzien van bijna alleen biologische of lokale producten, ook bieden we onze gasten graag een plantaardig alternatief.', 'Bij ons zit duurzaamheid verstopt in alles wat we doen. De horeca is voorzien van bijna alleen biologische of lokale producten, ook bieden we onze gasten graag een plantaardig alternatief. We zijn vooral trots op onze heerlijke koffie van Koffie Station en de taarten van PS die CO2 neutraal bij ons worden geleverd. De werkplaats om fietsen te repareren spreekt voor zich, maar ook verkopen we een aantal fietsen van duurzame merken. Wat veel mensen niet weten is dat Spaak zich ook inzet voor een duurzamere stadslogistiek, zo hebben we meegewerkt aan het International Cargo Bike Festival. Onze ambitie is om in de toekomst ons meer in te zetten voor de duurzame stadslogistiek. Met regelmaat staat onze straat vol met bestelbusjes, dit is slecht voor de doorstroom, maar ook voor het milieu. ', 'Oude Boteringestraat', '66', '9712 GN', 'Groningen', '+31 50 211 3828', 'https://spaak.cc/'),
(24, 'WAAR', 'Soms is het best lastig te bedenken wat je een ander cadeau kan doen. Bij Waar kan je terecht voor een bijzonder cadeau met een verhaal.', 'Soms is het best lastig te bedenken wat je een ander cadeau kan doen. Bij Waar kan je terecht voor een bijzonder cadeau met een verhaal, want bijna alles bij deze cadeauwinkel is fairtrade of duurzaam. Ze verkopen onder andere mooie schrijfboekjes, kaarten, planten en verzorgingsproducten. ', 'Vismarkt', '10', '9711 KS', 'Groningen', '+31 50 305 0088', ''),
(25, 'Hartendief', 'Bij Hartendief kun je met een gerust hart winkelen met je kids. Deze mooie kinderwinkel is ruim opgezet zodat je hier gemakkelijk naar binnen kunt met een kinderwagen.', 'Bij Hartendief kun je met een gerust hart winkelen met je kids. Deze mooie kinderwinkel is ruim opgezet zodat je hier gemakkelijk naar binnen kunt met een kinderwagen. Daarnaast biedt Hartendief een ruim assortiment aan duurzame producten en kinderspeelgoed. ', 'Oosterstraat', '8', '9711 NT', 'Groningen', '+31 50 364 6260', 'https://www.hartendiefgroningen.nl/'),
(26, 'Pure Essensials', 'Benieuwd hoe duurzame en natuurlijke health en beauty producten kunnen bijdragen aan jouw gezondheid? Daar kunnen ze bij Pure Essentials alles over vertellen.', 'Benieuwd hoe duurzame en natuurlijke health en beauty producten kunnen bijdragen aan jouw gezondheid? Daar kunnen ze bij Pure Essentials alles over vertellen en ze geven graag advies. Het volledige assortiment van deze winkel heeft een natuurlijke oorsprong en waar mogelijk ook een biologische. Leuk om te weten over Pure Essentials is dat zij hun verpakkingsmateriaal hergebruiken voor de webshop. ', 'Zwanestraat', '16', '9712 CM', 'Groningen', '+31 50 360 3602', 'http://pure-essentials.nl/'),
(27, 'Artishock & Part of Art', 'Veel van de merken in deze twee naast elkaar gelegen damesmodezaken zijn van duurzame oorsprong. Bij het gehele assortiment is aandacht voor kwaliteit.', 'Veel van de merken in deze twee naast elkaar gelegen damesmodezaken zijn van duurzame oorsprong. Bij het gehele assortiment is aandacht voor kwaliteit. Het uitgangspunt is dan ook \"Beter 1 goed kledingstuk, dan meerdere van slechte kwaliteit.\" De ambitie van deze zaken is om in de toekomst duurzamer om te gaan met energie en verlichting. ', 'Zwanestraat', '8/10', '9712 CL', 'Groningen', '+31 50 313 5937', 'http://www.artishockgroningen.nl/'),
(28, 'Stardust', 'De dames van Stardust hebben een passie voor vintage, want niks is leuker dan een kledingstuk een tweede of misschien wel een derde of vierde leven te geven.', 'De dames van Stardust hebben een passie voor vintage, want niks is leuker dan een kledingstuk een tweede of misschien wel een derde of vierde leven te geven. Daarnaast kan je in de winkel een aantal duurzame Groningse merken vinden en remade kleding. Stardust heeft ook mooie ambities. Ze willen graag af van de plastic kledinghangers en deze inruilen voor gerecycled houten hangers. Daarbij zijn ze bezig met een webshop waar ze aandacht gaan besteden aan een duurzaam logistiek proces. \r\n', 'Carolieweg', '13', '9711 LP', 'Groningen', '+31 50 750 3362', 'http://www.stardust-store.nl/'),
(29, 'Beer&', 'Deze horecazaak is actief bezig met het reduceren van hun afval en dat doen ze op slimme manieren. Geen enkel gedeelte van hun vis, vlees of groente mag de prullenbak in.', 'Deze horecazaak is actief bezig met het reduceren van hun afval en dat doen ze op slimme manieren. Geen enkel gedeelte van hun vis, vlees of groente mag de prullenbak in. Zo maken ze heerlijke sauzen van visgraat en groentejus van groenteresten. Daarnaast zijn ze bezig met het ontwikkelen van een \'seitan\'. Dit is een vleesvervanger op basis van tarwe-eiwit, die zij ook graag bij andere horeca gelegenheden zouden willen aanbieden.', 'Rodeweg', '1', '9715 AW', 'Groningen', '+31 50 321 5030', 'https://beer-n.nl/diner'),
(30, 'MasMas', 'Bij de sfeervolle MasMas kan je terecht voor een lekkere bak koffie, vegan food & drinks, maar ook voor een gezellige spelletjesavond.', 'Bij de sfeervolle MasMas kan je terecht voor een lekkere bak koffie, vegan food & drinks, maar ook voor een gezellige spelletjesavond. De ondernemer achter MasMas adviseert om klein te beginnen met verduurzamen. Pak op wat bij je past en wees trots op de stappen die je maakt, alle beetjes helpen. Leuk om te weten is dat je bij MasMas je plant een nieuw leven kan geven. ', 'Oude Kijk in Het Jatstraat', '65', '9712 EE', 'Groningen', '-', 'https://www.facebook.com/masmas.gro/'),
(31, 'Marquant', 'De man die van jeans en casuals houdt kan terecht bij Marquant voor een aantal mooie duurzame merken. Veel merken die je vindt in deze winkel hebben een duurzame oorsprong.', 'De man die van jeans en casuals houdt kan terecht bij Marquant voor een aantal mooie duurzame merken. Veel merken die je vindt in deze winkel hebben een duurzame oorsprong. Ook besteedt deze winkel aandacht aan duurzaamheid in de winkel, denk aan het gebruik van Led-verlichting en het dichthouden van de deur in de winter. ', 'Oude Boteringestraat', '3', '9712 GA', 'Groningen', '+31 50 318 1604', 'https://www.marquant-groningen.nl/'),
(32, 'Zich Zach', 'Deze damesmodezaak heeft een enorm divers assortiment. Je kan hier namelijk nieuwe kleding en tweedehands kleding kopen.', 'Deze damesmodezaak heeft een enorm divers assortiment. Je kan hier namelijk nieuwe kleding en tweedehands kleding kopen. Een gedeelte van de nieuwe kleding heeft een duurzame oorsprong. De tweedehands collectie bestaat uit speciaal geselecteerde items die bij de consument passen. De ambitie van Zich Zach is om de komende jaren verder te verduurzamen door bijvoorbeeld de verlichting in de winkel aan te passen. ', 'Gelkingestraat 43, 9711 NB Groningen', '43', '9711 NB', 'Groningen', '+31 50 314 6163', 'https://www.zichzachgroningen.com/'),
(33, 'Feel Good', 'Feel Good is een heerlijke all-day ontbijt en lunch tent, waar zo eerlijk mogelijk eten wordt verkocht. Er worden ook diverse vegan opties aangeboden.', 'Feel Good is een heerlijke all-day ontbijt en lunch tent, waar zo eerlijk mogelijk eten wordt verkocht. Er worden ook diverse vegan opties aangeboden en zo is er voor iedereen wat wils. Naast ontbijt en lunch kan je ook elke werkdag eten wat de pot schaft. Feel Good probeert op zo\'n manier in te kopen, dat er zo min mogelijk wordt verspild en doet moeite om plastic te vermijden. ', 'Oude Kijk in Het Jatstraat', '29', '9712 EB', 'Groningen', '+31 6 36368139', 'https://www.feelgoodgroningen.nl/'),
(34, 'The Student Hotel', 'Ook een hotel op onze route die stappen zet in duurzaamheid. De gebruikelijke dingen als de gasten verzoeken hun handdoeken vaker te gebruiken en meer.', 'Ook een hotel op onze route die stappen zet in duurzaamheid. De gebruikelijke dingen als de gasten verzoeken hun handdoeken vaker te gebruiken en de room key die zorgt dat bij afwezigheid het licht uitgaat spreken natuurlijk voor zich. Wat leuk is om te weten is dat The Student Hotel bewust gebruikt maakt van houten tandenborstels en dat er een samenwerking is met Clean the World. Deze organisatie haalt gebruikte zeepjes van het hotel op en vermaalt deze tot nieuwe zeepjes die vervolgens in een hygi&#235;ne kit worden uitgedeeld in Afrika. Ook heeft The Student Hotel een Bike-Sharing systeem. Wanneer de fietsen beginnen te slijten worden deze door het fietsenmerk Roetz ge-refurbished zodat ze opnieuw gebruikt kunnen worden. ', 'Boterdiep', '9', '9712 LH', 'Groningen', '+31 50 206 9161', 'https://www.thestudenthotel.com/groningen/'),
(35, 'Haastje Repje', 'Een damesmodezaak waar duurzaamheid zich op alle gebieden laat zien. Een groot gedeelte van het assortiment van Haasje Repje heeft een duurzame oorsprong.', 'Een damesmodezaak waar duurzaamheid zich op alle gebieden laat zien. Een groot gedeelte van het assortiment van Haasje Repje heeft een duurzame oorsprong. De medewerkers kunnen je alles vertellen over de materialen en geven ook graag advies over duurzaam wassen. Voor Haasje Repje is het dan ook meer dan logisch dat het personeel met de fiets komt, er geen plastic tasjes gebruikt worden en de winkel is voorzien van led verlichting. Wat ook leuk is om te weten dat de rest partijen van Haasje Repje naar Kledingbank Maxima gaan. ', 'Gelkingestraat', '41', '9711 NB', 'Groningen', '+31 50 313 7698', 'http://www.haastje-repje.nl/'),
(36, 'Liatelier', 'Deze prachtig sieranden- en cadeau winkel verkoopt het liefst producten met een bijzondere waarde. In de winkel kun je fairtrade, gerecycled en vooral tijdloze sieraden vinden.', 'Deze prachtig sieranden- en cadeau winkel verkoopt het liefst producten met een bijzondere waarde. In de winkel kun je fairtrade, gerecycled en vooral tijdloze sieraden vinden. De winkel kiest er bewust voor om uitsluitend edelstenen te gebruiken en niet-synthetische geverfde stenen. Ook heeft deze winkel een zogenaamde sieradendokter, die je graag helpt jouw sieraden te repareren en weer als nieuw te maken.', 'Vismarkt 48, 9711 KV Groningen', '48', '9711 KV', 'Groningen', '+31 50 311 7567', 'http://www.liatelier.nl/'),
(37, 'Expresso', 'Deze damesmodeketen heeft stappen gemaakt in duurzaamheid door zich aan te sluiten bij de \'Fair Wear Foundation\'. Dit betekent dat er aan geen enkel kledingstuk kinderhandjes te pas zijn gekomen. ', 'Deze damesmodeketen heeft stappen gemaakt in duurzaamheid door zich aan te sluiten bij de \'Fair Wear Foundation\'. Dit betekent dat er aan geen enkel kledingstuk kinderhandjes te pas zijn gekomen. Daarnaast is er bij sommige items in de winkel gebruik gemaakt van petflessen en gerecyclede kleding. Dit om de afvalberg kleiner te maken. Ook doet Expresso donaties aan goede doelen.', 'Herestraat', '50', '9711 LK', 'Groningen', '+31 50 311 8912', 'https://www.expresso.nl/'),
(38, 'HEMA', 'Ook HEMA maakt stappen naar een duurzamer assortiment. Waar eerder al veel kinderkleding van biologisch katoen werd gemaakt, is vanaf dit seizoen al het gebruikte katoen bij HEMA duurzaam.', 'Ook HEMA maakt stappen naar een duurzamer assortiment. Waar eerder al veel kinderkleding van biologisch katoen werd gemaakt, is vanaf dit seizoen al het gebruikte katoen bij HEMA duurzaam. Hierdoor worden er minder bestrijdingsmiddelen en water gebruikt bij de landbouw. Daarnaast is het leuk om te weten dat HEMA de katoenboeren ondersteunt bij deze verandering en zich inzet voor betere arbeidsomstandigheden tijdens het productieproces.', 'Herestraat', '64', '9711 LK', 'Groningen', '+31 50 318 1441', 'https://www.hema.nl/'),
(39, 'Steps', 'Steps is zich bewust geworden van de impact van de kleidingindustrie op het milieu. Daarom stelt Steps hoge eisen aan de kwaliteit van het productieproces.', 'Steps is zich bewust geworden van de impact van de kleidingindustrie op het milieu. Daarom stelt Steps hoge eisen aan de kwaliteit van het productieproces en biedt een aantal duurzame alternatieven voor polyester, viscose, katoen en denim. #nextsteps', 'Herestraat', '35', '9711 LB', 'Groningen', '+31 50 205 0133', 'https://www.steps.nl/'),
(40, 'PIECES', 'PIECES steunt het Better Cotton Intiative (BCI). Dit is het grootste duurzaamheidsprogramma in de wereld als het gaat om katoen.', 'PIECES steunt het Better Cotton Intiative (BCI). Dit is het grootste duurzaamheidsprogramma in de wereld als het gaat om katoen. BCI zorgt ervoor dat iedereen van boeren, textielverwerkers tot retailers samenwerkt om Better Cotton nog duurzamer en toegankelijker te maken. Ook richt PIECES zich op de verhoging van het gebruik van gerecyclede textielvezels. \'We werken eraan om klimaatpositief te zijn, eerlijk voor iedereen en circulair van opzet\'.', 'Herestraat 13, 9711 LA Groningen', '13', '9711 LA', 'Groningen', '+31 50 318 2520', 'https://www.pieces.com/nl/nl/home'),
(41, 'Jack & Jones', 'Net als PIECES steunt Jack & Jones het Better Cotton Intiative (BCI). Dit is het grootste duurzaamheidsprogramma in de wereld als het gaat om katoen.', 'Net als PIECES steunt Jack & Jones het Better Cotton Intiative (BCI). Dit is het grootste duurzaamheidsprogramma in de wereld als het gaat om katoen. BCI zorgt ervoor dat iedereen van boeren, textielverwerkers tot retailers samenwerkt om Better Cotton nog duurzamer en toegankelijker te maken. Ook richt Jack & Jones zich op de verhoging van het gebruik van gerecyclede textielvezels. \'We werken eraan om klimaatpositief te zijn, eerlijk voor iedereen en circulair van opzet\'.', 'Herestraat', '14', '9711 LJ', 'Groningen', '+31 50 313 2307', 'https://www.jackjones.com/nl/nl/home');

-- --------------------------------------------------------

--
-- Tabelstructuur voor tabel `winkel_evenement`
--

CREATE TABLE `winkel_evenement` (
  `id` int(10) NOT NULL,
  `evenement_naam` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `dag` int(11) NOT NULL,
  `datum` date NOT NULL,
  `tijd` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `plaats` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `adres` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `kost` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `beschrijving_kort` longtext COLLATE utf8_unicode_ci NOT NULL,
  `beschrijving` longtext COLLATE utf8_unicode_ci NOT NULL,
  `beschrijving_engels` longtext COLLATE utf8_unicode_ci NOT NULL,
  `facebook_link` varchar(255) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Gegevens worden geëxporteerd voor tabel `winkel_evenement`
--

INSERT INTO `winkel_evenement` (`id`, `evenement_naam`, `dag`, `datum`, `tijd`, `plaats`, `adres`, `kost`, `beschrijving_kort`, `beschrijving`, `beschrijving_engels`, `facebook_link`) VALUES
(1, 'Workshop Indoor Gardening', 28, '2019-09-28', '16.00 - 17.30', 'Lust', 'Oude Kijk in Het Jatstraat 58, 9712 EL Groningen', 'Entrance &#8364;3,50 (incl. a pastry with coffee/tea)', 'Dit evenement is Engelstalig. We beginnen met het praten over duurzaamheid, dan een discussiepanel over tuinieren en we eindigen met een quiz.', 'Dit evenement is Engelstalig.\r\n<br/><br/>\r\nWe beginnen met het praten over duurzaamheid, dan hebben we een discussiepanel met 2 tuinliefhebbers, praten we over de do\'s en don\'ts van tuinieren en aan het einde hebben we een quiz over het onderwerp. Voor de winnaars hebben we 4 verrassingsprijzen om hen te helpen hun eigen tuin te beginnen.', 'This event will be held in English.\r\n<br/><br/>\r\nWe\'ll start by talking about sustainability, then we have a discussion panel with 2 gardening lovers, we talk about dos and don\'ts of gardening and finally we have a quiz about the topic. For the winners, we have 4 surprise prizes to help them start their own garden.\r\n', 'https://www.facebook.com/events/666118010560372/'),
(2, 'Oddity: Oddity kleding inlevering', 28, '2019-09-28', '10.00 - 17.00', 'Oddity', 'Oosterstraat 16, 9711 NT Groningen', 'Gratis toegang/Free entrance', 'Bij Oddity zijn duurzaamheid en fair fashion belangrijke onderwerpen. Tijdens SuMoFest krijg je bij inlevering van oude Oddity kleding korting op je nieuwe aanschaf.', 'Bij Oddity zijn duurzaamheid en fair fashion belangrijke onderwerpen. Ze blijven zoeken naar prachtige, trendsettende en duurzame merken. Tijdens (SuMoFest en) het Oosterstraatfeest krijg je bij inlevering van oude Oddity kleding -mits in goede staat- 30% van het verkoopbedrag als korting op je nieuwe aanschaf. Nieuwe klanten zullen een mooie korting ontvangen op een kleurworkshop bij besteding van &#8364;100,-  of meer. Kom dus langs in deze prachtige winkel!', 'No English translation', 'https://www.facebook.com/odditywear.nl'),
(3, 'Artishock & Part of Art: Kleuranalyse', 28, '2019-09-28', '13.00 - 17.00', 'Artishock & Part of Art', 'Zwanestraat 8/10, 9712 CL Groningen', 'Gratis toegang/Free entrance', 'De dameszaken Artichock & Part of Art kopen kleding in van hoogwaardige kwaliteit. Kom tijdens het SuMoFest langs en laat je informeren door een kleuranalyst die jou kan vertellen welke kleur het beste bij je past.', 'De dameszaken Artichock & Part of Art kopen kleding in van hoogwaardige kwaliteit. Zij vinden het belangrijk dat een prachtig kledingstuk meerdere seizoenen meegaat. Ook zij zijn altijd op zoek naar duurzame merken. Het merk Filippa K is daar een goed voorbeeld van en zit dan ook al jaren in hun collectie. Kom op de zaterdag tijdens het SuMoFest naar deze mooie zaken en laat je informeren door een kleuranalyst die jou kan vertellen welke kleur het beste bij je past. Daarbij zal er een waardebon van &#8364;150,- worden verloot onder alle klanten die die dag een aankoop doen in de winkel. Dit alles onder het genot van een hapje en een drankje. Zeker een bezoekje waard dus!', 'No English translation', 'https://www.facebook.com/PartofArtArtishock'),
(4, 'Diezijner: \"Het leuke omruilrekje\"', 29, '2019-09-29', '10.00 - 17.00', 'Diezijner', 'Zwanestraat 29, 9712 CJ Groningen', 'Gratis toegang/Free entrance', 'Bij DieZijner vind je tijdloze kleding die met aandacht is gemaakt. Tijdens SuMoFest zul je bij DieZijner \"Het leuke omruilrekje\" vinden.', 'Bij DieZijner vind je tijdloze kleding die met aandacht is gemaakt. Alle kleding bij DieZijner is dan ook van natuurlijke materialen gemaakt. Tijdens SuMoFest zul je bij DieZijner \"Het leuke omruilrekje\" vinden. Hier kun je een mooi kledingstuk -passend bij het DieZijner assortiment- achterlaten en je mag er vervolgens een ander kledingstuk van het rek voor meenemen. Daarbij krijg je -in het weekend van 28 en 29 september-  eenmalig 15% korting op 1 item naar keuze uit het nieuwe assortiment, wanneer je een mooi kledingstuk achterlaat. Na dit weekend kan dit nog steeds, dan krijg je 10% korting. Deze actie loopt tot 31 oktober. \r\n<br/><br/>\r\nDiezijner doet ook mee aan de duurzame modeshow op de Grote markt en heeft een grabbelton in de winkel, vol mooi duurzame cadeaus, waar iedereen die een aankoop heeft gedaan een cadeau uit mag grabbelen. \r\n<br/><br/>\r\nDaarbij komt op zondag 29 september schrijfster Karen Kammeraat een lezing geven. Ze zal tijdens de lezing veel handvatten geven voor een duurzame lifestyle. Het zal een motiverende lezing worden met volop praktische tips. Aansluitend zal er een heerlijke vegan lunch buffet geserveerd worden.\r\nDe lezing begint om 11:00u (inloop vanaf 10:30u). De lunch zal aansluitend zijn om 12:00u.\r\n<br/><br/>\r\nSchuif je aan? De kosten voor de lunch met lezing zijn &#8364;7,50. Geef je op voor 25 september door een mail te sturen naar <a href=\"mailto:info@diezijner.eu\" class=\"a-leesmeer\" target=\"_blank\">info@diezijner.eu</a>\r\n', 'No English translation', 'https://www.facebook.com/events/375754169762465/'),
(5, 'Heksenketel: Closet Sale', 28, '2019-09-28', '10.00 - 17.30', 'Heksenketel', 'Folkingestraat 12b, 9711 JW Groningen', 'Gratis toegang/Free entrance', 'De Heksenketel verkoopt met een team van 11 mensen hun unieke, lokaal gemaakte kleding, op een prachtige plek in Groningen: De Folkingestraat! Tijdens SuMoFEST introduceren zij een closet sale.', 'De Heksenketel verkoopt met een team van 11 mensen hun unieke, lokaal gemaakte kleding, op een prachtige plek in Groningen: De Folkingestraat! Tijdens SuMoFEST introduceren zij een closet sale: een rek met prettig geprijsde kleding, uniek en handgemaakt door henzelf! Zoals ze zelf zeggen: \'Het mes snijdt aan twee kanten: jij een uniek, handgemaakt item voor weinig, wij geen dumping in de kledingcontainer. Samen zijn we duurzaam!\'', 'No English translation', 'https://www.facebook.com/heksenketelmode'),
(6, 'Heksenketel: Closet Sale', 29, '2019-09-29', '12.30 - 16.30', 'Heksenketel', 'Folkingestraat 12b, 9711 JW Groningen', 'Gratis toegang/Free entrance', 'De Heksenketel verkoopt met een team van 11 mensen hun unieke, lokaal gemaakte kleding, op een prachtige plek in Groningen: De Folkingestraat! Tijdens SuMoFEST introduceren zij een closet sale.', 'De Heksenketel verkoopt met een team van 11 mensen hun unieke, lokaal gemaakte kleding, op een prachtige plek in Groningen: De Folkingestraat! Tijdens SuMoFEST introduceren zij een closet sale: een rek met prettig geprijsde kleding, uniek en handgemaakt door henzelf! Zoals ze zelf zeggen: \'Het mes snijdt aan twee kanten: jij een uniek, handgemaakt item voor weinig, wij geen dumping in de kledingcontainer. Samen zijn we duurzaam!\'', 'No English translation', 'https://www.facebook.com/heksenketelmode'),
(7, 'Heksenketel: Closet Sale', 30, '2019-09-30', '13.00 - 17.00', 'Heksenketel', 'Folkingestraat 12b, 9711 JW Groningen', 'Gratis toegang/Free entrance', 'De Heksenketel verkoopt met een team van 11 mensen hun unieke, lokaal gemaakte kleding, op een prachtige plek in Groningen: De Folkingestraat! Tijdens SuMoFEST introduceren zij een closet sale.', 'De Heksenketel verkoopt met een team van 11 mensen hun unieke, lokaal gemaakte kleding, op een prachtige plek in Groningen: De Folkingestraat! Tijdens SuMoFEST introduceren zij een closet sale: een rek met prettig geprijsde kleding, uniek en handgemaakt door henzelf! Zoals ze zelf zeggen: \'Het mes snijdt aan twee kanten: jij een uniek, handgemaakt item voor weinig, wij geen dumping in de kledingcontainer. Samen zijn we duurzaam!\'', 'No English translation', 'https://www.facebook.com/heksenketelmode'),
(8, 'Heksenketel: Closet Sale', 1, '2019-10-01', '10.00 - 18.00', 'Heksenketel', 'Folkingestraat 12b, 9711 JW Groningen', 'Gratis toegang/Free entrance', 'De Heksenketel verkoopt met een team van 11 mensen hun unieke, lokaal gemaakte kleding, op een prachtige plek in Groningen: De Folkingestraat! Tijdens SuMoFEST introduceren zij een closet sale.', 'De Heksenketel verkoopt met een team van 11 mensen hun unieke, lokaal gemaakte kleding, op een prachtige plek in Groningen: De Folkingestraat! Tijdens SuMoFEST introduceren zij een closet sale: een rek met prettig geprijsde kleding, uniek en handgemaakt door henzelf! Zoals ze zelf zeggen: \'Het mes snijdt aan twee kanten: jij een uniek, handgemaakt item voor weinig, wij geen dumping in de kledingcontainer. Samen zijn we duurzaam!\'', 'No English translation', 'https://www.facebook.com/heksenketelmode'),
(9, 'Heksenketel: Closet Sale', 2, '2019-10-02', '10.00 - 18.00', 'Heksenketel', 'Folkingestraat 12b, 9711 JW Groningen', 'Gratis toegang/Free entrance', 'De Heksenketel verkoopt met een team van 11 mensen hun unieke, lokaal gemaakte kleding, op een prachtige plek in Groningen: De Folkingestraat! Tijdens SuMoFEST introduceren zij een closet sale.', 'De Heksenketel verkoopt met een team van 11 mensen hun unieke, lokaal gemaakte kleding, op een prachtige plek in Groningen: De Folkingestraat! Tijdens SuMoFEST introduceren zij een closet sale: een rek met prettig geprijsde kleding, uniek en handgemaakt door henzelf! Zoals ze zelf zeggen: \'Het mes snijdt aan twee kanten: jij een uniek, handgemaakt item voor weinig, wij geen dumping in de kledingcontainer. Samen zijn we duurzaam!\'', 'No English translation', 'https://www.facebook.com/heksenketelmode'),
(10, 'Heksenketel: Closet Sale', 3, '2019-10-03', '10.00 - 18.00', 'Heksenketel', 'Folkingestraat 12b, 9711 JW Groningen', 'Gratis toegang/Free entrance', 'De Heksenketel verkoopt met een team van 11 mensen hun unieke, lokaal gemaakte kleding, op een prachtige plek in Groningen: De Folkingestraat! Tijdens SuMoFEST introduceren zij een closet sale.', 'De Heksenketel verkoopt met een team van 11 mensen hun unieke, lokaal gemaakte kleding, op een prachtige plek in Groningen: De Folkingestraat! Tijdens SuMoFEST introduceren zij een closet sale: een rek met prettig geprijsde kleding, uniek en handgemaakt door henzelf! Zoals ze zelf zeggen: \'Het mes snijdt aan twee kanten: jij een uniek, handgemaakt item voor weinig, wij geen dumping in de kledingcontainer. Samen zijn we duurzaam!\'', 'No English translation', 'https://www.facebook.com/heksenketelmode'),
(12, 'Heksenketel: Closet Sale', 4, '2019-10-04', '10.00 - 18.00', 'Heksenketel', 'Folkingestraat 12b, 9711 JW Groningen', 'Gratis toegang/Free entrance', 'De Heksenketel verkoopt met een team van 11 mensen hun unieke, lokaal gemaakte kleding, op een prachtige plek in Groningen: De Folkingestraat! Tijdens SuMoFEST introduceren zij een closet sale.', 'De Heksenketel verkoopt met een team van 11 mensen hun unieke, lokaal gemaakte kleding, op een prachtige plek in Groningen: De Folkingestraat! Tijdens SuMoFEST introduceren zij een closet sale: een rek met prettig geprijsde kleding, uniek en handgemaakt door henzelf! Zoals ze zelf zeggen: \'Het mes snijdt aan twee kanten: jij een uniek, handgemaakt item voor weinig, wij geen dumping in de kledingcontainer. Samen zijn we duurzaam!\'', 'No English translation', 'https://www.facebook.com/heksenketelmode'),
(13, 'Heksenketel: Closet Sale', 5, '2019-10-05', '10.00 - 17.30', 'Heksenketel', 'Folkingestraat 12b, 9711 JW Groningen', 'Gratis toegang/Free entrance', 'De Heksenketel verkoopt met een team van 11 mensen hun unieke, lokaal gemaakte kleding, op een prachtige plek in Groningen: De Folkingestraat! Tijdens SuMoFEST introduceren zij een closet sale.', 'De Heksenketel verkoopt met een team van 11 mensen hun unieke, lokaal gemaakte kleding, op een prachtige plek in Groningen: De Folkingestraat! Tijdens SuMoFEST introduceren zij een closet sale: een rek met prettig geprijsde kleding, uniek en handgemaakt door henzelf! Zoals ze zelf zeggen: \'Het mes snijdt aan twee kanten: jij een uniek, handgemaakt item voor weinig, wij geen dumping in de kledingcontainer. Samen zijn we duurzaam!\'', 'No English translation', 'https://www.facebook.com/heksenketelmode');

--
-- Indexen voor geëxporteerde tabellen
--

--
-- Indexen voor tabel `evenement`
--
ALTER TABLE `evenement`
  ADD PRIMARY KEY (`id`);

--
-- Indexen voor tabel `winkels`
--
ALTER TABLE `winkels`
  ADD PRIMARY KEY (`id`);

--
-- Indexen voor tabel `winkel_evenement`
--
ALTER TABLE `winkel_evenement`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT voor geëxporteerde tabellen
--

--
-- AUTO_INCREMENT voor een tabel `evenement`
--
ALTER TABLE `evenement`
  MODIFY `id` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=13;

--
-- AUTO_INCREMENT voor een tabel `winkels`
--
ALTER TABLE `winkels`
  MODIFY `id` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=42;

--
-- AUTO_INCREMENT voor een tabel `winkel_evenement`
--
ALTER TABLE `winkel_evenement`
  MODIFY `id` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=14;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
