-- phpMyAdmin SQL Dump
-- version 4.8.3
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Gegenereerd op: 24 sep 2019 om 15:39
-- Serverversie: 10.1.36-MariaDB
-- PHP-versie: 7.2.11

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `sustainablemoments`
--

-- --------------------------------------------------------

--
-- Tabelstructuur voor tabel `winkels`
--

CREATE TABLE `winkels` (
  `id` int(10) NOT NULL,
  `winkel_naam` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `beschrijving_kort` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `beschrijving` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `straat_naam` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `straat_nummer` char(10) COLLATE utf8_unicode_ci NOT NULL,
  `postcode` char(7) COLLATE utf8_unicode_ci NOT NULL,
  `stad` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `telefoon` char(15) COLLATE utf8_unicode_ci NOT NULL,
  `website` varchar(255) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Gegevens worden geëxporteerd voor tabel `winkels`
--

INSERT INTO `winkels` (`id`, `winkel_naam`, `beschrijving_kort`, `beschrijving`, `straat_naam`, `straat_nummer`, `postcode`, `stad`, `telefoon`, `website`) VALUES
(1, 'De Musjes ', 'Met het kopen bij deze kinderkledingwinkel help je als consument de planeet. Het assortiment van Musjes is namelijk vrij van kinderarbeid en garandeert fairtrade productie en natuurlijke materialen.', 'Met het kopen bij deze kinderkledingwinkel help je als consument de planeet. Het assortiment van Musjes is namelijk vrij van kinderarbeid en garandeert fairtrade productie en natuurlijke materialen. Musjes gaat zich de komende tijd bezighouden met de verduurzaming van de toelevering naar de winkel om zo nog groener te worden.', 'Zwanestraat', '25', '9712 CJ', 'Groningen', '+31 50 785 0720', 'https://www.musjes.com/'),
(2, 'Marquant Department ', 'Een winkel met prachtige merkkleding, waarvan het grootste gedeelte van kleding van duurzame merken afkomstig is. Ook kan je deze winkel vinden in de app \"Eerlijk winkelen\".', 'Een winkel met prachtige merkkleding, waarvan het grootste gedeelte van kleding van duurzame merken afkomstig is. Ook kan je deze winkel vinden in de app \"Eerlijk winkelen\". De ambitie van Marquant Department is om hun volledige assortiment duurzaam in te kopen.  ', 'Oude Boteringestraat', '1-1', '9712 GA', 'Groningen', '+31 50 230 3062', 'https://www.marquant-department.nl/'),
(3, 'Het Land van Kokanje', 'Dit restaurant gebruikt alternatieve bereidingswijzen om hiermee afval te verminderen. Daarnaast kan je hier genieten van heerlijke gerechten gemaakt met seizoensproducten.', 'Dit restaurant gebruikt alternatieve bereidingswijzen om hiermee afval te verminderen. Daarnaast kan je hier genieten van heerlijke gerechten gemaakt met seizoensproducten. Het Land van Kokanje focust zich al op de vermindering van gas en stroom, maar hebben de ambitie hun pand beter te isoleren om hiermee nog meer te besparen. ', 'Oude Boteringestraat', '9', '9712 GB', 'Groningen', '+31 50 318 0622', 'https://www.landvankokanje.nl/'),
(4, 'Simsalabim', 'Deze eigengereide winkel heeft een prachtig assortiment aan duurzame merken. Simsalabim let bij inkoop op natuurlijke materialen en de werkomstandigheden waarin de kleding wordt gemaakt.', 'Deze eigengereide winkel heeft een prachtig assortiment aan duurzame merken. Simsalabim let bij inkoop op natuurlijke materialen en de werkomstandigheden waarin de kleding wordt gemaakt. Uiteraard krijg je die goede kleding alleen mee naar huis is een papieren tasje. ', 'Folkingestraat', '12', '9711 JW', 'Groningen', '+31 50 312 3727', 'https://simsalabimwebshop.com/'),
(5, 'Tim Tom', 'Iets wat als hobby begon veranderde in een stijlvolle woonwinkel met een prachtig assortiment aan tweedehands meubels en woonaccessoires. Alle producten van Tim Tom krijgen bij hun klanten een nieuw leven. ', 'Iets wat als hobby begon veranderde in een stijlvolle woonwinkel met een prachtig assortiment aan tweedehands meubels en woonaccessoires. Alle producten van Tim Tom krijgen bij hun klanten een nieuw leven. Wat leuk is om te weten dat Tim Tom hun verpakkingsmateriaal zoveel mogelijk hergebruikt. Zo komt alles netjes, maar ook milieuvriendelijk bij de klant. ', 'Nieuwe Ebbingestraat', '19', '9712 NC', 'Groningen', '+31 6 50915888', 'https://www.tim-tom.nl/'),
(6, 'Heksenketel', 'Deze damesmode zaak wordt gerund door Groningse modemakers. Dit betekent een assortiment van lokale producten die CO2 neutraal in de winkel komen.', 'Deze damesmode zaak wordt gerund door Groningse modemakers. Dit betekent een assortiment van lokale producten die CO2 neutraal in de winkel komen. Daarnaast heb je de kans om in Heksenketel de maker te ontmoeten. Wist je trouwens dat door het kopen bij deze kleinschalige makers dit gepaard gaat met veel minder afval? ', 'Folkingestraat', '12b', '9711 JW', 'Groningen', '+31 50 313 6690', 'http://www.heksenketelmode.nl/'),
(7, 'Mary Jane Schoenenboetiek', 'Deze chique boetiek verkoopt voornamelijk schoenen die ambachtelijk worden gemaakt in kleinschalige Europese fabrieken. Ook zijn er bij Mary Jane vegan schoenen te vinden.', 'Deze chique boetiek verkoopt voornamelijk schoenen die ambachtelijk worden gemaakt in kleinschalige Europese fabrieken. Ook zijn er bij Mary Jane vegan schoenen te vinden. De ondernemers achter Mary Jane snappen de struggle van andere ondernemers omtrent duurzaamheid, maar adviseren je niet tegen te laten houden! Elke stap naar duurzaamheid is er 1 en het hoeft dus niet allemaal in 1 keer perfect. De ambitie van Mary Jane is om een eigen duurzame collectie te ontwikkelen. ', 'Oosterstraat', '23', '9711 NN', 'Groningen', '+31 50 280 7592', 'https://www.maryjaneboetiek.com/'),
(8, 'DieZijner', 'Dit is een kledingzaak met aandacht voor de klant. Het assortiment van DieZijner kenmerkt zich aan tijdloze kleding die met aandacht is gemaakt.', 'Dit is een kledingzaak met aandacht voor de klant. Het assortiment van DieZijner kenmerkt zich aan tijdloze kleding die met aandacht is gemaakt. Zo vind je alleen kledingstukken van natuurlijke materialen in deze winkel. Ook is er aandacht voor toelevering door duurzaam transport en duurzame energie in de winkel. Het liefste wil Die Zijner in de toekomst samenwerken met andere ondernemingen om de verpakkingsmateriaal van binnenkomende en uitgaande goederen te verduurzamen. ', 'Zwanestraat', '29', '9712 CJ', 'Groningen', '+31 6 34569089', 'http://diezijner.eu/'),
(9, 'Stadsakker', 'Of je nu opzoek bent naar potgrond, een boeket, groentes, eieren of tuingereedschap. De Stadsakker heeft voor ieder wat wils een duurzame oplossing.', 'Of je nu opzoek bent naar potgrond, een boeket, groentes, eieren of tuingereedschap. De Stadsakker heeft voor ieder wat wils een duurzame oplossing. Ook is de Stadsakker een leerbedrijf waar nieuwe kleinschalige kwekers worden opgeleid. Leuk is om te weten dat de Stadsakker geen groentes weggooien, dit wordt namelijk kippenvoer. En ja je kan ook hun eitjes bij de Stadsakker kopen. Verser kan niet! ', 'Oude Kijk in Het Jatstraat', '38', '9712 EK', 'Groningen', '+31 50 313 1739', 'http://www.stadsakker.nl/'),
(10, 'Schone Zaken', 'Deze modezaak is al sinds 1997 pioiner en specialist in Eco-Bio-Fairwear kleding. Dit zie je uiteraard terug in een assortiment van 100% verantwoorde kleding.', 'Deze modezaak is al sinds 1997 pioiner en specialist in Eco-Bio-Fairwear kleding. Dit zie je uiteraard terug in een assortiment van 100% verantwoorde kleding. Tijdens Sustainable Moments heb je een mooie kans om deze eco-producten eens uit te proberen, door een mooie aanbieding op bamboe sokken. ', 'Nieuwe Ebbingestraat', '16', '9712 NK', 'Groningen', '+31 50 589 1515', 'http://www.schonezaken.nl/'),
(11, 'Terre Des Hommes ', 'Een tweedehands zaak met een breed assortiment aan spullen. Denk hierbij aan boeken, spelletjes en kleding.', 'Een tweedehands zaak met een breed assortiment aan spullen. Denk hierbij aan boeken, spelletjes en kleding. Al het geld wat verdiend wordt bij Terre Des hommes wordt gebruikt om uitbuiting van kinderen te stoppen.', 'Nieuwe Ebbingestraat', '83', '9712 NG', 'Groningen', '+31 50 577 0112', 'https://www.terredeshommes.nl/winkels/groningen'),
(12, 'De Groene Stoel', 'De naam van de zaak laat al zien hoe groen het hart is van de ondernemer achter De Groene Stoel is. Ze werken samen met lokale en duurzame bedrijven.', 'De naam van de zaak laat al zien hoe groen het hart is van de ondernemer achter De Groene Stoel is. Ze werken samen met lokale en duurzame bedrijven. Daarnaast bieden ze een vernieuwend traject aan om \"nieuwe Groningers\" te helpen integreren in onze samenleving en op de arbeidsmarkt.', 'Gedempte Zuiderdiep', '26', '9711 HH', 'Groningen', '+31 50 230 2628', 'https://www.degroenestoel.nl/'),
(13, 'De Proof', 'Je kan zelfs in Groningen een duurzame kapsalon vinden! Het assortiment shampoos die je bij De Proof kan vinden, hebben een duurzame verpakking.', 'Je kan zelfs in Groningen een duurzame kapsalon vinden! Het assortiment shampoos die je bij De Proof kan vinden, hebben een duurzame verpakking. Daarnaast besteedt De Proof aandacht aan het verduurzamen van de winkel, dit door middel van infrarood verwarming. De Proof heeft de ambitie om nieuwe douchekoppen aan te schaffen die bijdragen het water en energieverbruik van de zaak te verminderen. De duurzame tip van de ondernemer is: Begin bij jezelf, hoe meer jij je verdiept hoe leuker het wordt. Praat er ook over met je klanten, dit is een gegarandeerd succes! ', 'Grote Kromme Elleboog', '3', '9712 BJ', 'Groningen', '+31 50 230 0861', 'http://the-proof.nl/'),
(14, 'Laif & Nuver', 'Deze prachtige woonwinkel heeft hun eerste stappen gemaakt in het verduurzamen van hun winkel. Dit door duurzaam om te gaan met energie en het hergebruiken van verpakkingen.', 'Deze prachtige woonwinkel heeft hun eerste stappen gemaakt in het verduurzamen van hun winkel. Dit door duurzaam om te gaan met energie en het hergebruiken van verpakkingen. Laif & Nuver heeft de ambitie om een nieuw pand te vinden die volledig duurzaam functioneert.', 'Vismarkt', '40', '9711 KT', 'Groningen', '+31 50 850 0562', 'https://www.laifennuver.nl/'),
(15, 'Oddity', 'Dames kunnen van alles vinden bij Oddity; duurzame merken, tweedehands kleding en zelfs met regelmaat live muziek. Daarnaast is Oddity intern bewust bezig.', 'Dames kunnen van alles vinden bij Oddity; duurzame merken, tweedehands kleding en zelfs met regelmaat live muziek. Daarnaast is Oddity intern bewust bezig. De inrichting de winkel is tweedehands en medewerkers komen uitsluitend met het OV naar hun werk. Oddity heeft de ambitie om te innoveren, om zo duurzame kleding laagdrempelig aan te bieden. Deze plannen zijn in de maak.', 'Oosterstraat', '16', '9711 NT', 'Groningen', '+31 50 750 1497', 'https://m.facebook.com/odditywear.nl'),
(16, 'KOKOTOKO', 'Hier staat duurzaamheid in alle opzichten centraal. Waardoor je alle producten van KOKOTOKO met een gerust hart kunt aanschaffen.', 'Hier staat duurzaamheid in alle opzichten centraal. Waardoor je alle producten van KOKOTOKO met een gerust hart kunt aanschaffen. Alle dames en heren kleding is namelijk fairtrade en biologisch gecertificeerd. Ook kan je bij KOKOTOKO diverse lifestyle producten kopen, die je op weg helpen met het verduurzamen van je leven. Ondanks deze mooie producten worden deze alsnog in plastic aangeleverd, KOKOTOKO wil hier graag een oplossing voor vinden.', 'Oosterstraat', '26', '9711 NV', 'Groningen', '-', 'http://kokotoko.nl/'),
(17, 'ReShare Store', 'Dit initiatief van Het Leger Des Heils is begonnen in Groningen en heeft ondertussen 10 winkels door het hele land verspreid. Alles in de winkel is tweedehands inclusief het interieur.', 'Dit initiatief van Het Leger Des Heils is begonnen in Groningen en heeft ondertussen 10 winkels door het hele land verspreid. Alles in de winkel is tweedehands inclusief het interieur. Ook wordt er bewust omgegaan met logistiek. Daarnaast krijgt de klant zijn aankopen uitsluitend mee in een papieren tasje.', 'Oosterstraat', '41', '9711 NR', 'Groningen', '+31 50 360 3333', 'https://www.resharestore.nl/index.php'),
(18, 'BAQ', 'Bij BAQ kan je genieten van heerlijk brood, taart en koek, die elke ochtend vers gebakken worden in de eigen bakkerij.', 'Bij BAQ kan je genieten van heerlijk brood, taart en koek, die elke ochtend vers gebakken worden in de eigen bakkerij. BAQ maakt gebruik van lokale grondstoffen, zo kunnen ze je precies vertellen waar jouw broodje vandaan komt/ Hiermee steun je de Groningse economie.', 'Folkingestraat', '19', '9711 JS', 'Groningen', '+31 50 553 5911', 'https://www.baq.nl/'),
(19, 'Find050', 'Find your treasures bij Find050. Deze tweedehands kledingwinkel geeft jouw kleding weer een tweede leven.', 'Find your treasures bij Find050. Deze tweedehands kledingwinkel geeft jouw kleding weer een tweede leven. Ja, je leest het goed. Je kan bij Find050 ook zelf winkeltje spelen. Je brengt jouw pareltjes die te lang niet uit de kast zijn gekomen naar Find en daar mag het dan een aantal weken in de winkel hangen. Wordt het verkocht krijg je een gedeelte van de opbrengst, zo niet gaat jouw kleding naar Kledingbank Maxima of je neemt je items zelf weer mee naar huis. Op deze manier help je hier ook weer een ander mee.', 'Damsterdiep', '42', '9711 SM', 'Groningen', '+31 6 20449374', 'https://www.findvintage.nl/'),
(20, 'MAHALO', 'Deze pas geopende lunchzaak zet zich in voor jouw gezondheid en het milieu. Zo verkoopt Mahalo alleen biologische en plantaardige producten.', 'Deze pas geopende lunchzaak zet zich in voor jouw gezondheid en het milieu. Zo verkoopt Mahalo alleen biologische en plantaardige producten die ook overwegend lokaal geproduceerd zijn. Daarnaast is het leuk om te weten dat het take-away materiaal van Mahalo biologisch afbreekbaar is en dat ze spoedig elektrisch zullen koken.', 'Verlengde Grachtstraat', '1', '9717 GD', 'Groningen', '-', 'http://www.mahalo.nu/'),
(21, 'MamaMini', 'Een bekende naam in Groningen. Dat is ook niet zo gek, want Mamamini is namelijk niet zomaar een kringloopwinkel.', 'Een bekende naam in Groningen. Dat is ook niet zo gek, want Mamamini is namelijk niet zomaar een kringloopwinkel. Bijna alle opbrengsten van Mamamini gaan weer terug naar Groningers. Ieder jaar wordt een doel gekozen, zoals bijvoorbeeld juridische ondersteuning voor minima. Daarnaast scheidt Mamamini al het afval van de producten die de winkel niet halen en worden er laagdrempelige werkplekken gecre?erd.', 'Damsterdiep', '307', '9713 EH', 'Groningen', '+31 50 313 2200', 'https://www.mamamini.nl/'),
(22, 'Cledingraad', 'Een mooie mannenmode zaak met een prachtig pand in de binnenstad. Mannen kunnen bij Cledingraad terecht voor diverse duurzame merken.', 'Een mooie mannenmode zaak met een prachtig pand in de binnenstad. Mannen kunnen bij Cledingraad terecht voor diverse duurzame merken, zoals ook een aantal merken die je niet in andere winkels op onze winkelroute kan vinden. Cledingraad heeft de ambitie om hun volledige collectie nog verder te verduurzamen.', 'Zwanestraat', '9', '9712 CH', 'Groningen', '+31 50 851 1855', 'http://www.cledingraad.nl/'),
(23, 'Spaak', 'Bij ons zit duurzaamheid verstopt in alles wat we doen. De horeca is voorzien van bijna alleen biologische of lokale producten, ook bieden we onze gasten graag een plantaardig alternatief.', 'Bij ons zit duurzaamheid verstopt in alles wat we doen. De horeca is voorzien van bijna alleen biologische of lokale producten, ook bieden we onze gasten graag een plantaardig alternatief. We zijn vooral trots op onze heerlijke koffie van Koffie Station en de taarten van PS die CO2 neutraal bij ons worden geleverd. De werkplaats om fietsen te repareren spreekt voor zich, maar ook verkopen we een aantal fietsen van duurzame merken. Wat veel mensen niet weten is dat Spaak zich ook inzet voor een duurzamere stadslogistiek, zo hebben we meegewerkt aan het International Cargo Bike Festival. Onze ambitie is om in de toekomst ons meer in te zetten voor de duurzame stadslogistiek. Met regelmaat staat onze straat vol met bestelbusjes, dit is slecht voor de doorstroom, maar ook voor het milieu. ', 'Oude Boteringestraat', '66', '9712 GN', 'Groningen', '+31 50 211 3828', 'https://spaak.cc/'),
(24, 'WAAR', 'Soms is het best lastig te bedenken wat je een ander cadeau kan doen. Bij Waar kan je terecht voor een bijzonder cadeau met een verhaal.', 'Soms is het best lastig te bedenken wat je een ander cadeau kan doen. Bij Waar kan je terecht voor een bijzonder cadeau met een verhaal, want bijna alles bij deze cadeauwinkel is fairtrade of duurzaam. Ze verkopen onder andere mooie schrijfboekjes, kaarten, planten en verzorgingsproducten. ', 'Vismarkt', '10', '9711 KS', 'Groningen', '+31 50 305 0088', ''),
(25, 'Hartendief', 'Bij Hartendief kun je met een gerust hart winkelen met je kids. Deze mooie kinderwinkel is ruim opgezet zodat je hier gemakkelijk naar binnen kunt met een kinderwagen.', 'Bij Hartendief kun je met een gerust hart winkelen met je kids. Deze mooie kinderwinkel is ruim opgezet zodat je hier gemakkelijk naar binnen kunt met een kinderwagen. Daarnaast biedt Hartendief een ruim assortiment aan duurzame producten en kinderspeelgoed. ', 'Oosterstraat', '8', '9711 NT', 'Groningen', '+31 50 364 6260', 'https://www.hartendiefgroningen.nl/'),
(26, 'Pure Essensials', 'Benieuwd hoe duurzame en natuurlijke health en beauty producten kunnen bijdragen aan jouw gezondheid? Daar kunnen ze bij Pure Essentials alles over vertellen.', 'Benieuwd hoe duurzame en natuurlijke health en beauty producten kunnen bijdragen aan jouw gezondheid? Daar kunnen ze bij Pure Essentials alles over vertellen en ze geven graag advies. Het volledige assortiment van deze winkel heeft een natuurlijke oorsprong en waar mogelijk ook een biologische. Leuk om te weten over Pure Essentials is dat zij hun verpakkingsmateriaal hergebruiken voor de webshop. ', 'Zwanestraat', '16', '9712 CM', 'Groningen', '+31 50 360 3602', 'http://pure-essentials.nl/'),
(27, 'Artishock & Part of Art', 'Veel van de merken in deze twee naast elkaar gelegen damesmodezaken zijn van duurzame oorsprong. Bij het gehele assortiment is aandacht voor kwaliteit.', 'Veel van de merken in deze twee naast elkaar gelegen damesmodezaken zijn van duurzame oorsprong. Bij het gehele assortiment is aandacht voor kwaliteit. Het uitgangspunt is dan ook \"Beter 1 goed kledingstuk, dan meerdere van slechte kwaliteit.\" De ambitie van deze zaken is om in de toekomst duurzamer om te gaan met energie en verlichting. ', 'Zwanestraat', '8/10', '9712 CL', 'Groningen', '+31 50 313 5937', 'http://www.artishockgroningen.nl/'),
(28, 'Stardust', 'De dames van Stardust hebben een passie voor vintage, want niks is leuker dan een kledingstuk een tweede of misschien wel een derde of vierde leven te geven.', 'De dames van Stardust hebben een passie voor vintage, want niks is leuker dan een kledingstuk een tweede of misschien wel een derde of vierde leven te geven. Daarnaast kan je in de winkel een aantal duurzame Groningse merken vinden en remade kleding. Stardust heeft ook mooie ambities. Ze willen graag af van de plastic kledinghangers en deze inruilen voor gerecycled houten hangers. Daarbij zijn ze bezig met een webshop waar ze aandacht gaan besteden aan een duurzaam logistiek proces. \r\n', 'Carolieweg', '13', '9711 LP', 'Groningen', '+31 50 750 3362', 'http://www.stardust-store.nl/'),
(29, 'Beer&', 'Deze horecazaak is actief bezig met het reduceren van hun afval en dat doen ze op slimme manieren. Geen enkel gedeelte van hun vis, vlees of groente mag de prullenbak in.', 'Deze horecazaak is actief bezig met het reduceren van hun afval en dat doen ze op slimme manieren. Geen enkel gedeelte van hun vis, vlees of groente mag de prullenbak in. Zo maken ze heerlijke sauzen van visgraat en groentejus van groenteresten. Daarnaast zijn ze bezig met het ontwikkelen van een \'seitan\'. Dit is een vleesvervanger op basis van tarwe-eiwit, die zij ook graag bij andere horeca gelegenheden zouden willen aanbieden.', 'Rodeweg', '1', '9715 AW', 'Groningen', '+31 50 321 5030', 'https://beer-n.nl/diner'),
(30, 'MasMas', 'Bij de sfeervolle MasMas kan je terecht voor een lekkere bak koffie, vegan food & drinks, maar ook voor een gezellige spelletjesavond.', 'Bij de sfeervolle MasMas kan je terecht voor een lekkere bak koffie, vegan food & drinks, maar ook voor een gezellige spelletjesavond. De ondernemer achter MasMas adviseert om klein te beginnen met verduurzamen. Pak op wat bij je past en wees trots op de stappen die je maakt, alle beetjes helpen. Leuk om te weten is dat je bij MasMas je plant een nieuw leven kan geven. ', 'Oude Kijk in Het Jatstraat', '65', '9712 EE', 'Groningen', '-', 'https://www.facebook.com/masmas.gro/'),
(31, 'Marquant', 'De man die van jeans en casuals houdt kan terecht bij Marquant voor een aantal mooie duurzame merken. Veel merken die je vindt in deze winkel hebben een duurzame oorsprong.', 'De man die van jeans en casuals houdt kan terecht bij Marquant voor een aantal mooie duurzame merken. Veel merken die je vindt in deze winkel hebben een duurzame oorsprong. Ook besteedt deze winkel aandacht aan duurzaamheid in de winkel, denk aan het gebruik van Led-verlichting en het dichthouden van de deur in de winter. ', 'Oude Boteringestraat', '3', '9712 GA', 'Groningen', '+31 50 318 1604', 'https://www.marquant-groningen.nl/'),
(32, 'Zich Zach', 'Deze damesmodezaak heeft een enorm divers assortiment. Je kan hier namelijk nieuwe kleding en tweedehands kleding kopen.', 'Deze damesmodezaak heeft een enorm divers assortiment. Je kan hier namelijk nieuwe kleding en tweedehands kleding kopen. Een gedeelte van de nieuwe kleding heeft een duurzame oorsprong. De tweedehands collectie bestaat uit speciaal geselecteerde items die bij de consument passen. De ambitie van Zich Zach is om de komende jaren verder te verduurzamen door bijvoorbeeld de verlichting in de winkel aan te passen. ', 'Gelkingestraat 43, 9711 NB Groningen', '43', '9711 NB', 'Groningen', '+31 50 314 6163', 'https://www.zichzachgroningen.com/'),
(33, 'Feel Good', 'Feel Good is een heerlijke all-day ontbijt en lunch tent, waar zo eerlijk mogelijk eten wordt verkocht. Er worden ook diverse vegan opties aangeboden.', 'Feel Good is een heerlijke all-day ontbijt en lunch tent, waar zo eerlijk mogelijk eten wordt verkocht. Er worden ook diverse vegan opties aangeboden en zo is er voor iedereen wat wils. Naast ontbijt en lunch kan je ook elke werkdag eten wat de pot schaft. Feel Good probeert op zo\'n manier in te kopen, dat er zo min mogelijk wordt verspild en doet moeite om plastic te vermijden. ', 'Oude Kijk in Het Jatstraat', '29', '9712 EB', 'Groningen', '+31 6 36368139', 'https://www.feelgoodgroningen.nl/'),
(34, 'The Student Hotel', 'Ook een hotel op onze route die stappen zet in duurzaamheid. De gebruikelijke dingen als de gasten verzoeken hun handdoeken vaker te gebruiken en meer.', 'Ook een hotel op onze route die stappen zet in duurzaamheid. De gebruikelijke dingen als de gasten verzoeken hun handdoeken vaker te gebruiken en de room key die zorgt dat bij afwezigheid het licht uitgaat spreken natuurlijk voor zich. Wat leuk is om te weten is dat The Student Hotel bewust gebruikt maakt van houten tandenborstels en dat er een samenwerking is met Clean the World. Deze organisatie haalt gebruikte zeepjes van het hotel op en vermaalt deze tot nieuwe zeepjes die vervolgens in een hygi&#235;ne kit worden uitgedeeld in Afrika. Ook heeft The Student Hotel een Bike-Sharing systeem. Wanneer de fietsen beginnen te slijten worden deze door het fietsenmerk Roetz ge-refurbished zodat ze opnieuw gebruikt kunnen worden. ', 'Boterdiep', '9', '9712 LH', 'Groningen', '+31 50 206 9161', 'https://www.thestudenthotel.com/groningen/'),
(35, 'Haastje Repje', 'Een damesmodezaak waar duurzaamheid zich op alle gebieden laat zien. Een groot gedeelte van het assortiment van Haasje Repje heeft een duurzame oorsprong.', 'Een damesmodezaak waar duurzaamheid zich op alle gebieden laat zien. Een groot gedeelte van het assortiment van Haasje Repje heeft een duurzame oorsprong. De medewerkers kunnen je alles vertellen over de materialen en geven ook graag advies over duurzaam wassen. Voor Haasje Repje is het dan ook meer dan logisch dat het personeel met de fiets komt, er geen plastic tasjes gebruikt worden en de winkel is voorzien van led verlichting. Wat ook leuk is om te weten dat de rest partijen van Haasje Repje naar Kledingbank Maxima gaan. ', 'Gelkingestraat', '41', '9711 NB', 'Groningen', '+31 50 313 7698', 'http://www.haastje-repje.nl/'),
(36, 'Liatelier', 'Deze prachtig sieranden- en cadeau winkel verkoopt het liefst producten met een bijzondere waarde. In de winkel kun je fairtrade, gerecycled en vooral tijdloze sieraden vinden.', 'Deze prachtig sieranden- en cadeau winkel verkoopt het liefst producten met een bijzondere waarde. In de winkel kun je fairtrade, gerecycled en vooral tijdloze sieraden vinden. De winkel kiest er bewust voor om uitsluitend edelstenen te gebruiken en niet-synthetische geverfde stenen. Ook heeft deze winkel een zogenaamde sieradendokter, die je graag helpt jouw sieraden te repareren en weer als nieuw te maken.', 'Vismarkt 48, 9711 KV Groningen', '48', '9711 KV', 'Groningen', '+31 50 311 7567', 'http://www.liatelier.nl/'),
(37, 'Expresso', 'Deze damesmodeketen heeft stappen gemaakt in duurzaamheid door zich aan te sluiten bij de \'Fair Wear Foundation\'. Dit betekent dat er aan geen enkel kledingstuk kinderhandjes te pas zijn gekomen. ', 'Deze damesmodeketen heeft stappen gemaakt in duurzaamheid door zich aan te sluiten bij de \'Fair Wear Foundation\'. Dit betekent dat er aan geen enkel kledingstuk kinderhandjes te pas zijn gekomen. Daarnaast is er bij sommige items in de winkel gebruik gemaakt van petflessen en gerecyclede kleding. Dit om de afvalberg kleiner te maken. Ook doet Expresso donaties aan goede doelen.', 'Herestraat', '50', '9711 LK', 'Groningen', '+31 50 311 8912', 'https://www.expresso.nl/'),
(38, 'HEMA', 'Ook HEMA maakt stappen naar een duurzamer assortiment. Waar eerder al veel kinderkleding van biologisch katoen werd gemaakt, is vanaf dit seizoen al het gebruikte katoen bij HEMA duurzaam.', 'Ook HEMA maakt stappen naar een duurzamer assortiment. Waar eerder al veel kinderkleding van biologisch katoen werd gemaakt, is vanaf dit seizoen al het gebruikte katoen bij HEMA duurzaam. Hierdoor worden er minder bestrijdingsmiddelen en water gebruikt bij de landbouw. Daarnaast is het leuk om te weten dat HEMA de katoenboeren ondersteunt bij deze verandering en zich inzet voor betere arbeidsomstandigheden tijdens het productieproces.', 'Herestraat', '64', '9711 LK', 'Groningen', '+31 50 318 1441', 'https://www.hema.nl/'),
(39, 'Steps', 'Steps is zich bewust geworden van de impact van de kleidingindustrie op het milieu. Daarom stelt Steps hoge eisen aan de kwaliteit van het productieproces.', 'Steps is zich bewust geworden van de impact van de kleidingindustrie op het milieu. Daarom stelt Steps hoge eisen aan de kwaliteit van het productieproces en biedt een aantal duurzame alternatieven voor polyester, viscose, katoen en denim. #nextsteps', 'Herestraat', '35', '9711 LB', 'Groningen', '+31 50 205 0133', 'https://www.steps.nl/'),
(40, 'PIECES', 'PIECES steunt het Better Cotton Intiative (BCI). Dit is het grootste duurzaamheidsprogramma in de wereld als het gaat om katoen.', 'PIECES steunt het Better Cotton Intiative (BCI). Dit is het grootste duurzaamheidsprogramma in de wereld als het gaat om katoen. BCI zorgt ervoor dat iedereen van boeren, textielverwerkers tot retailers samenwerkt om Better Cotton nog duurzamer en toegankelijker te maken. Ook richt PIECES zich op de verhoging van het gebruik van gerecyclede textielvezels. \'We werken eraan om klimaatpositief te zijn, eerlijk voor iedereen en circulair van opzet\'.', 'Herestraat 13, 9711 LA Groningen', '13', '9711 LA', 'Groningen', '+31 50 318 2520', 'https://www.pieces.com/nl/nl/home'),
(41, 'Jack & Jones', 'Net als PIECES steunt Jack & Jones het Better Cotton Intiative (BCI). Dit is het grootste duurzaamheidsprogramma in de wereld als het gaat om katoen.', 'Net als PIECES steunt Jack & Jones het Better Cotton Intiative (BCI). Dit is het grootste duurzaamheidsprogramma in de wereld als het gaat om katoen. BCI zorgt ervoor dat iedereen van boeren, textielverwerkers tot retailers samenwerkt om Better Cotton nog duurzamer en toegankelijker te maken. Ook richt Jack & Jones zich op de verhoging van het gebruik van gerecyclede textielvezels. \'We werken eraan om klimaatpositief te zijn, eerlijk voor iedereen en circulair van opzet\'.', 'Herestraat', '14', '9711 LJ', 'Groningen', '+31 50 313 2307', 'https://www.jackjones.com/nl/nl/home');

--
-- Indexen voor geëxporteerde tabellen
--

--
-- Indexen voor tabel `winkels`
--
ALTER TABLE `winkels`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT voor geëxporteerde tabellen
--

--
-- AUTO_INCREMENT voor een tabel `winkels`
--
ALTER TABLE `winkels`
  MODIFY `id` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=42;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
